# Generated by Django 2.0.6 on 2018-06-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
