# Generated by Django 2.0.6 on 2018-06-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='prueba',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
